apiVersion: v1
kind: Pod
metadata:
  labels:
    key: value
    test: "true"
  name: foo-pod-1
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    imagePullPolicy: Always
    name: busybox
  restartPolicy: Always
