apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "quarks-job.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quarks-job
  template:
    metadata:
      labels:
        name: quarks-job
    spec:
      serviceAccountName: {{ template "quarks-job.serviceAccountName" . }}
      containers:
        - name: quarks-job
          image: "{{ .Values.image.org }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - quarks-job
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: CF_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "quarks-job"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 2999
              scheme: "HTTPS"
            initialDelaySeconds: 2
