apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarks-job-persist-output
  {{- if .Values.global.operator.watchNamespace }}
  namespace: {{ .Values.global.operator.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
