apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: quarks-job-persist-output
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
- apiGroups:
  - quarks.cloudfoundry.org
  resources:
  - quarksjobs
  verbs:
  - get
