kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quarks-job
subjects:
- kind: ServiceAccount
  name: quarks-job
roleRef:
  kind: Role
  name: quarks-job
  apiGroup: rbac.authorization.k8s.io
